#!/usr/bin/env python3

import argparse
import json
import os
import subprocess


def generate_linux_dts(csr_json, dts, initrd, root_device):
    # Add the repository-pinned LiteX packages to sys.path only when generation
    # starts, so --help remains available before submodules are initialized.
    import vendor  # noqa: F401
    from litex.tools.litex_json2dts_linux import generate_dts

    with open(csr_json, encoding="utf-8") as json_file:
        csr_data = json.load(json_file)

    dts_content = generate_dts(
        csr_data,
        initrd=initrd,
        polling=False,
        root_device=root_device,
    )

    dts_dir = os.path.dirname(os.path.abspath(dts))
    os.makedirs(dts_dir, exist_ok=True)
    with open(dts, "w", encoding="utf-8") as dts_file:
        dts_file.write(dts_content)


def compile_dts(dts, dtb):
    dtb_dir = os.path.dirname(os.path.abspath(dtb))
    os.makedirs(dtb_dir, exist_ok=True)
    subprocess.run(["dtc", "-O", "dtb", "-o", dtb, dts], check=True)


def main():
    parser = argparse.ArgumentParser(
        description="Generate the Linux device tree for the Analogue Pocket LiteX SoC."
    )
    parser.add_argument(
        "--csr-json",
        default=os.path.join("build", "litex", "csr.json"),
        help="LiteX CSR JSON generated by analogue_pocket.py --linux.",
    )
    parser.add_argument(
        "--dts",
        default=os.path.join("build", "litex", "pocket.dts"),
        help="Device-tree source output path.",
    )
    parser.add_argument(
        "--dtb",
        default=os.path.join("build", "litex", "pocket.dtb"),
        help="Compiled device-tree blob output path.",
    )
    parser.add_argument(
        "--initrd",
        default="enabled",
        help="Initramfs path, or enabled/disabled for LiteX default placement.",
    )
    parser.add_argument(
        "--root-device",
        default="ram0",
        help="Linux root device passed to the LiteX DTS generator.",
    )
    parser.add_argument(
        "--no-compile",
        action="store_true",
        help="Generate pocket.dts without invoking dtc.",
    )
    args = parser.parse_args()

    generate_linux_dts(
        csr_json=args.csr_json,
        dts=args.dts,
        initrd=args.initrd,
        root_device=args.root_device,
    )
    if not args.no_compile:
        compile_dts(args.dts, args.dtb)


if __name__ == "__main__":
    main()
