#!/usr/bin/env python3

import argparse
import json
import os


EXPECTED_CONSTANTS = {
    "config_clock_frequency": 57_120_000,
    "config_cpu_count": 1,
    "config_cpu_isa": "rv32i2p0_mafdc",
    "config_cpu_mmu": "sv32",
    "config_cpu_dcache_size": 4096,
    "config_cpu_dcache_ways": 1,
    "config_cpu_icache_size": 4096,
    "config_cpu_icache_ways": 1,
    "config_cpu_dtlb_size": 4,
    "config_cpu_dtlb_ways": 4,
    "config_cpu_itlb_size": 4,
    "config_cpu_itlb_ways": 4,
    "config_cpu_interrupts": 3,
    "rom_boot_address": 0x40F00000,
    "timer0_interrupt": 1,
    "uart_interrupt": 2,
}

REQUIRED_CONSTANTS = (
    "config_cpu_type_vexriscv_smp",
    "config_cpu_variant_linux",
)

EXPECTED_CSR_BASES = {
    "uart": 0xF0001000,
    "timer0": 0xF0001800,
}

EXPECTED_MEMORIES = {
    "rom": (0x00000000, 0x00020000),
    "sram": (0x10000000, 0x00002000),
    "main_ram": (0x40000000, 0x04000000),
    "opensbi": (0x40F00000, 0x00080000),
    "csr": (0xF0000000, 0x00010000),
    "clint": (0xF0010000, 0x00010000),
    "plic": (0xF0C00000, 0x00400000),
}


def as_integer(value):
    if isinstance(value, str):
        return int(value, 0)
    return value


def validate_linux_config(csr_data):
    errors = []
    constants = csr_data.get("constants", {})
    csr_bases = csr_data.get("csr_bases", {})
    memories = csr_data.get("memories", {})

    for name, expected in EXPECTED_CONSTANTS.items():
        actual = constants.get(name)
        if isinstance(expected, int) and actual is not None:
            actual = as_integer(actual)
        if actual != expected:
            errors.append(f"constant {name}: expected {expected!r}, got {actual!r}")

    for name in REQUIRED_CONSTANTS:
        if name not in constants:
            errors.append(f"constant {name}: missing")

    if "video_framebuffer_base" in constants:
        errors.append(
            "constant video_framebuffer_base: Linux build must not reserve a framebuffer"
        )

    for name, expected in EXPECTED_CSR_BASES.items():
        actual = csr_bases.get(name)
        if actual is not None:
            actual = as_integer(actual)
        if actual != expected:
            actual_text = "missing" if actual is None else f"0x{actual:08x}"
            errors.append(f"CSR {name}: expected 0x{expected:08x}, got {actual_text}")

    for name, (expected_base, expected_size) in EXPECTED_MEMORIES.items():
        memory = memories.get(name)
        if memory is None:
            errors.append(f"memory {name}: missing")
            continue
        if "base" not in memory or "size" not in memory:
            errors.append(f"memory {name}: base or size missing")
            continue
        actual_base = as_integer(memory["base"])
        actual_size = as_integer(memory["size"])
        if (actual_base, actual_size) != (expected_base, expected_size):
            errors.append(
                f"memory {name}: expected 0x{expected_base:08x}+0x{expected_size:x}, "
                f"got 0x{actual_base:08x}+0x{actual_size:x}"
            )

    return errors


def main():
    parser = argparse.ArgumentParser(
        description="Validate the generated Analogue Pocket Linux LiteX configuration."
    )
    parser.add_argument(
        "--csr-json",
        default=os.path.join("build", "litex", "csr.json"),
        help="LiteX CSR JSON generated by analogue_pocket.py --linux.",
    )
    args = parser.parse_args()

    with open(args.csr_json, encoding="utf-8") as json_file:
        csr_data = json.load(json_file)

    errors = validate_linux_config(csr_data)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        raise SystemExit(1)

    print("Linux LiteX configuration matches the Pocket hardware contract.")


if __name__ == "__main__":
    main()
